name: Build Xaga Kernel (esk)

on:
  workflow_dispatch:

    inputs:
      KERNEL_SOURCE:
        description: 'Kernel Source'
        required: true
        default: 'xiaomi-mediatek-devs/android_kernel_xiaomi_mt6895'
      KERNEL_SOURCE_BRANCH:
        description: 'Branch'
        required: true
        default: 'lineage-22.1'      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          
    - name: Setup Configuration
      run: |
        echo "KERNEL_SOURCE=${{ github.event.inputs.KERNEL_SOURCE }}" >> $GITHUB_ENV
        echo "KERNEL_SOURCE_BRANCH=${{ github.event.inputs.KERNEL_SOURCE_BRANCH }}" >> $GITHUB_ENV

    
    - name: Setup build kernel environment
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install git flex lzop bison make libssl-dev python3 python-is-python3 libncurses-dev dos2unix



    - name: Download Clang Toolchain
      run: |
        wget https://github.com/Mandi-Sa/clang/releases/download/amd64-kernel-arm_static-22/llvm22.0.0-binutils2.45.1_amd64-kernel-arm_static-20251214.7z
        mkdir clang && cd clang
        7za x ../*.7z

    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        github-server-url: 'https://github.com'
        repository: ${{ env.KERNEL_SOURCE }}
        ref: ${{ env.KERNEL_SOURCE_BRANCH }}
        path: project
        submodules: recursive
        fetch-depth: 1
            
    - name: Setup Patches
      run: |
        cd project
        sed -i 's/drivers\/input\/misc\/aw8697_haptic\/Kconfig/drivers\/input\/misc\/aw8697_haptic\/Kconfig\"/g' drivers/input/misc/Kconfig
        sed -i 's/drivers\/input\/misc\/aw8624_haptic\/Kconfig/drivers\/input\/misc\/aw8624_haptic\/Kconfig\"/g' drivers/input/misc/Kconfig
        dos2unix drivers/input/touchscreen/goodix_9916/Kconfig
        sed -i 's/-dirty//g' scripts/setlocalversion
        {
            echo "CONFIG_BPF_STREAM_PARSER=y"
            echo "CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y"
            echo "CONFIG_NETFILTER_XT_SET=y"
            echo "CONFIG_IP_SET=y"
            echo "CONFIG_IP_SET_MAX=65534"
            echo "CONFIG_IP_SET_BITMAP_IP=y"
            echo "CONFIG_IP_SET_BITMAP_IPMAC=y"
            echo "CONFIG_IP_SET_BITMAP_PORT=y"
            echo "CONFIG_IP_SET_HASH_IP=y"
            echo "CONFIG_IP_SET_HASH_IPMARK=y"
            echo "CONFIG_IP_SET_HASH_IPPORT=y"
            echo "CONFIG_IP_SET_HASH_IPPORTIP=y"
            echo "CONFIG_IP_SET_HASH_IPPORTNET=y"
            echo "CONFIG_IP_SET_HASH_IPMAC=y"
            echo "CONFIG_IP_SET_HASH_MAC=y"
            echo "CONFIG_IP_SET_HASH_NETPORTNET=y"
            echo "CONFIG_IP_SET_HASH_NET=y"
            echo "CONFIG_IP_SET_HASH_NETNET=y"
            echo "CONFIG_IP_SET_HASH_NETPORT=y"
            echo "CONFIG_IP_SET_HASH_NETIFACE=y"
            echo "CONFIG_IP_SET_LIST_SET=y"
            echo "CONFIG_IP6_NF_NAT=y"
            echo "CONFIG_IP6_NF_TARGET_MASQUERADE=y"
          } >> ./arch/arm64/configs/gki_defconfig
          echo "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y" >> ./arch/arm64/configs/gki_defconfig
              
    - name: Build kernel
      run: |
        cd project
        export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
        export ARCH=arm64
        export SUBARCH=arm64
        make LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
          CC="clang" LD=ld.lld HOSTLD=ld.lld KCFLAGS+=-O2 \
          O=out gki_defconfig
        make LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- \
          CC="clang" LD=ld.lld HOSTLD=ld.lld KCFLAGS+=-O2 \
          O=out
    
    - name: Upload the kernel zip
      uses: actions/upload-artifact@v4
      with:
        name: xaga_${{ env.BUILD_TIME}}
        path: |
          /home/runner/work/My_KSU_Action/My_KSU_Action/project/out/arch/arm64/boot/*
